name: homl3
channels:
  - conda-forge
  - defaults
dependencies:
  - box2d-py  # used only in chapter 18, exercise 8
  - ftfy=5.5  # used only in chapter 16 by the transformers library
  - graphviz  # used only in chapter 6 for dot files
  - python-graphviz  # used only in chapter 6 for dot files
  - ipython=8.0  # a powerful Python shell
  - ipywidgets=7.6  # optionally used only in chapter 11 for tqdm in Jupyter
  - joblib=1.1  # used only in chapter 2 to save/load Scikit-Learn models
  - jupyterlab=3.2  # to edit and run Jupyter notebooks
  - matplotlib=3.5  # beautiful plots. See tutorial tools_matplotlib.ipynb
  - nbdime=3.1  # optional tool to diff Jupyter notebooks
  - nltk=3.6  # optionally used in chapter 3, exercise 4
  - numexpr=2.8  # used only in the Pandas tutorial for numerical expressions
  - numpy=1.22  # Powerful n-dimensional arrays and numerical computing tools
  - pandas=1.4  # data analysis and manipulation tool
  - pillow=9.0  # image manipulation library, (used by matplotlib.image.imread)
  - pip  # Python's package-management system
  - py-xgboost=1.5  # used only in chapter 6 for optimized Gradient Boosting
  - pyglet=1.5  # used only in chapter 18 to render environments
  - pyopengl=3.1  # used only in chapter 18 to render environments
  - python=3.9  # Python! Not using latest version as some libs lack support
  #- pyvirtualdisplay=2.2  # used only in chapter 18 if on headless server
  - requests=2.27  # used only in chapter 19 for REST API queries
  - scikit-learn=1.0  # machine learning library
  - scipy=1.8  # scientific/technical computing library
  - tqdm=4.62  # a progress bar library
  - wheel  # built-package format for pip
  - widgetsnbextension=3.5  # interactive HTML widgets for Jupyter notebooks
  - pip:
    - keras-tuner~=1.1.2  # used in chapters 10 and 19 for hyperparameter tuning
    - tensorboard-plugin-profile~=2.5.0  # profiling plugin for TensorBoard
    - tensorboard~=2.8.0  # TensorFlow's visualization toolkit
    - tensorflow-addons~=0.16.1  # used in chapters 11 & 16 (for AdamW & seq2seq)
    - tensorflow-datasets~=4.5.2  # datasets repository, ready to use
    - tensorflow-hub~=0.12.0  # trained ML models repository, ready to use
    - tensorflow-serving-api~=2.8.0  # or tensorflow-serving-api-gpu if gpu
    - tensorflow~=2.8.0  # Deep Learning library
    - transformers~=4.16.2  # Natural Language Processing lib for TF or PyTorch
    - urlextract~=1.5.0  # optionally used in chapter 3, exercise 4
    - gym[atari,accept-rom-license]~=0.21.0  # used only in chapter 18
    - google-cloud-aiplatform~=1.12.0  # used only in chapter 19
    - google-cloud-storage~=2.2.1  # used only in chapter 19
